### ISSUE TITLE
manjaro KDE 环境测有问题

### ISSUE THREAD

**Issue by RainNameless** [NoOne-hub/v2ray_client#1]
希望能够支持，我可以配合调试。

**Comment by NoOne-hub** [comment]
@RainNameless 已更新，测试下

**Comment by RainNameless** [comment]
Successfully installed gunicorn-19.9.0
./install.sh:行60: /etc/supervisor/conf.d/v2rayClient.conf: 没有那个文件或目录
Error: could not find config file /etc/supervisor/supervisord.conf
For help, use /usr/sbin/supervisord -h
接下来输入update,然后ctrl+d 退出
Error: could not find config file /etc/supervisor/supervisord.conf
For help, use /usr/sbin/supervisorctl -h
success
now you can open you web browser,open http://127.0.0.1:8000
It takes 0 minutes.

**Comment by NoOne-hub** [comment]
@RainNameless 查了下资料，发觉manjaro安装supervisor默认没配置文件，明天我在更新下，将配置文件写入

**Comment by RainNameless** [comment]
manjaro的virtualenv启动命令，我这里是activate，不是active，不知道是不是版本问题。

**Comment by RainNameless** [comment]
Requirement already satisfied: gunicorn in /usr/lib/python3.7/site-packages (19.9.0)
---------------------------------------------------------------------
Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.
---------------------------------------------------------------------
For help, use /usr/bin/supervisord -h
接下来输入update,然后ctrl+d 退出
supervisor> update
supervisor>
success
now you can open you web browser,open http://127.0.0.1:8000
It takes 0 minutes.
[pc v2ray_client]# ps -ef | grep supervisor
root      4615     1  0 23:40 ?        00:00:00 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
root      4944  3008  0 23:43 pts/2    00:00:00 grep --colour=auto supervisor
[pc v2ray_client]# ps -ef | grep v2ray
root      4511     1  0 23:39 ?        00:00:00 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
root      4948  3008  0 23:43 pts/2    00:00:00 grep --colour=auto v2ray
[pc v2ray_client]# lsof -i:8000
@NoOne-hub 
感觉manjaro的supervisor有坑，我也查查去。

**Comment by NoOne-hub** [comment]
@RainNameless 再次修改

**Comment by NoOne-hub** [comment]
> manjaro的virtualenv启动命令，我这里是activate，不是active，不知道是不是版本问题。
> 我用pip install的。

我的错，我打错了

**Comment by RainNameless** [comment]
啊,我好不容易调教好的supervisor，昨天因为不小心运行了你的卸载给干掉了,又报BUG了,我用虚拟机来测试下吧.晚一点给你答复.

**Comment by RainNameless** [comment]
环境VMware15.5Linux内核选择5.0以上：manjaro KDE运行内核5.2.11-1
manjaro KDE：第一次执行./install 运行supervisor报错,手动 pacman -S supervisor 了一次.
manjaro KDE：第二次执行的时候遇到个小bug,提示supervisor已经在监听.
manjaro KDE：我find / -name superviso.sock 发现在/run 目录下,unlink /run/superviso.sock 后
再执行./install 成功了！！！
先睡觉吧 明天在搞我的笔电！对了manjaro自带py3.7所以可以不用 加条判断吧virtualenv.

**Comment by RainNameless** [comment]
@NoOne-hub 抱歉刚刚看了下脚本哪些,发现uninstall.sh没删除supervisor.  
可能是之前的折腾supervisor衍生的问题.

**Comment by NoOne-hub** [comment]
> 环境VMware15.5Linux内核选择5.0以上：manjaro KDE运行内核5.2.11-1
> manjaro KDE：第一次执行./install 运行supervisor报错,手动 pacman -S supervisor 了一次.
> manjaro KDE：第二次执行的时候遇到个小bug,提示supervisor已经在监听.
> manjaro KDE：我find / -name superviso.sock 发现在/run 目录下,unlink /run/superviso.sock 后
> 再执行./install 成功了！！
> 先睡觉吧 明天再搞我的笔电！对了manjaro自带py3.7所以可以不用virtualenv 安装删了吧.

或许是因为没卸载supervisor的原因？

**Comment by RainNameless** [comment]
> > 环境VMware15.5Linux内核选择5.0以上：manjaro KDE运行内核5.2.11-1 
> > manjaro KDE：第一次执行。/install运行supervisor报错，手动pacman -Ssupervised一次。
> > manjaro KDE：第二次执行的时候遇到一个小bug，提示supervisor已经在监听。
> > manjaro KDE：我查找/ -name superviso.sock发现在/运行目录下，取消链接/run/superviso.sock后
> > 再执行./INSTALL成功了!! 
> > ！先睡觉吧明天再搞我的笔电对了manjaro自带py3.7所以可以不用virtualenv安装修改了吧。
> 
> 或许是因为没卸载上司的原因？

可
