### ISSUE TITLE
现在可以提出点界面上的建议吗

### ISSUE THREAD

**Issue by deepseer** [NoOne-hub/v2ray_client#12]
两点使用上的改进：

网页中的on和off差别太小了，订阅规模大起来以后很难在一长串列表中找出那个on。
可能的改进方案：
1. 增加一些排序、筛选功能，把on放在前面
2. 用颜色或者图标区分
3. 最简单的方法是把on改成长长的一串：\*\*\*\*\*\*\*\*\*on\*\*\*\*\*\*\*\*\*

建议增加一个功能
启动一个线路时，关闭其他线路连接
可以是一个放在列表顶端的开关，或者每个线路的行多出一个按钮（选择此线路并断开其他的）

**Comment by deepseer** [comment]
对了，第一个的方案3应该可以自己改吧……然而我没用过python，所以应该改哪里？

**Comment by NoOne-hub** [comment]
> 两点使用上的改进：
> 
> 网页中的on和off差别太小了，订阅规模大起来以后很难在一长串列表中找出那个on。
> 可能的改进方案：
> 
> 1. 增加一些排序、筛选功能，把on放在前面
> 2. 用颜色或者图标区分
> 3. 最简单的方法是把on改成长长的一串：*********on*********
> 
> 建议增加一个功能
> 启动一个线路时，关闭其他线路连接
> 可以是一个放在列表顶端的开关，或者每个线路的行多出一个按钮（选择此线路并断开其他的）

当然可以，这些会增加的，我觉得可以将启动的放到第一位，等我有时候在更新啊，周末和国庆这些时间

**Comment by NoOne-hub** [comment]
> 对了，第一个的方案3应该可以自己改吧……然而我没用过python，所以应该改哪里？

那个是改html的，前端部分

**Comment by NoOne-hub** [comment]
> 两点使用上的改进：
> 
> 网页中的on和off差别太小了，订阅规模大起来以后很难在一长串列表中找出那个on。
> 可能的改进方案：
> 
> 1. 增加一些排序、筛选功能，把on放在前面
> 2. 用颜色或者图标区分
> 3. 最简单的方法是把on改成长长的一串：*********on*********
> 
> 建议增加一个功能
> 启动一个线路时，关闭其他线路连接
> 可以是一个放在列表顶端的开关，或者每个线路的行多出一个按钮（选择此线路并断开其他的）

已更新
