### ISSUE TITLE
Unlinking stale socket /var/run/supervisor.sock

### ISSUE THREAD

**Issue by shizeying** [NoOne-hub/v2ray_client#13]
在centos7中安装成功之后还是会报Unlinking stale socket /var/run/supervisor.sock,在脚本执行完成之后,执行 supervisorctl start v2rayClient之后,先报Unlinking stale socket /var/run/supervisor.sock,通过此https://blog.csdn.net/tianjiewang/article/details/49481869解决之后,再重新supervisor之后,上面的错误会没有,但是会报v2rayClient: ERROR (no such process),这个要怎么解决呢

**Comment by NoOne-hub** [comment]
你是没用虚拟环境，用本机装的是吧，你卸载原来的supervisor没

**Comment by shizeying** [comment]
这个是个新系统

**Comment by shizeying** [comment]
vm虚拟机下装的centos7

**Comment by NoOne-hub** [comment]
unlink是在程序已经有进程的情况下会unlink，你可以ps -aux|grep supervisor查看进程，杀掉后重新启动试试

**Comment by shizeying** [comment]
命令是否和网上教程的是否一样,给个命令试试呢?

**Comment by NoOne-hub** [comment]
ps -aux|grep supervisord
kill -9 进程id号

**Comment by shizeying** [comment]
我的意思是启动的命令

**Comment by NoOne-hub** [comment]
你可以看下install里的supervisord部分

**Comment by shizeying** [comment]
root       3283  0.0  0.0 112728   980 pts/1    S+   15:04   0:00 grep --color=auto supervisord
我在kill的过程中,发现这个的pid是动态的,是没法kill的,要如何解决呢

**Comment by NoOne-hub** [comment]
这个不用kill，杀其余的就行

**Comment by shizeying** [comment]
我在kill掉之后,重新安装install中的操作重新进行了一遍,在执行supervisorctl start v2rayClient报了一下错误unix:///var/run/supervisor/supervisor.sock refused connection
![1](https://user-images.githubusercontent.com/38680988/65577978-7bbc9600-dfa7-11e9-9dd7-486fdf4cfc90.png)

**Comment by NoOne-hub** [comment]
加上配置试试supervisorctl -c 配置文件 start v2rayClient

**Comment by shizeying** [comment]
如果是supervisorctl -c /etc/supervisor/supervisord.conf start v2rayClient;还是会报上面的错误
;如果是v2rayClient.conf,汇报以下错误:
[root@localhost ~]# supervisorctl -c /etc/supervisor/conf.d/v2rayClient.conf start v2rayClient
Error: .ini file does not include supervisorctl section
For help, use /usr/bin/supervisorctl -h

**Comment by NoOne-hub** [comment]
你指定错配置文件了，在项目目录下config里有个配置文件

**Comment by shizeying** [comment]
不是这个文件supervisord.conf,那请问是:
app  app.db  config.py  images  install.sh  install_test.sh  migrations  README.md  requirements.txt  uninstall.sh  v2rayClient.py
这些里面的哪个呢?

**Comment by NoOne-hub** [comment]
我的错，少放了个文件夹，可能没写入成功。。你在这个目录下mkdir config吧，脚本里会写入的

**Comment by shizeying** [comment]
那我接下来需要怎么做呢

**Comment by NoOne-hub** [comment]
在执行次脚本

**Comment by shizeying** [comment]
需不需要从git上再次拉你的项目，执行过多次了，始终到这个问题卡住的

**Comment by shizeying** [comment]
我创建了config文件夹，但是并没有生成脚本呢,还是发生了相同的情况

**Comment by NoOne-hub** [comment]
你是运行install.sh?

**Comment by shizeying** [comment]
test

**Comment by NoOne-hub** [comment]
...，那是热心网友提供的，请运行install.sh

**Comment by NoOne-hub** [comment]
我更新了安装脚本

**Comment by shizeying** [comment]
还是pip3?

**Comment by NoOne-hub** [comment]
是的，用最新版本能解决大部分问题

**Comment by RainNameless** [comment]
> 还是PIP3？

抱歉没在centos上测试过，有问题吗！我等会瞧瞧去！

**Comment by RainNameless** [comment]
> 测试

抱歉没在centos上测试过，有问题吗！我等会瞧瞧去！

**Comment by shizeying** [comment]
好的 我感觉centos上的错误主要就是我遇到的这几个 你可以看下

**Comment by RainNameless** [comment]
> 好的我感觉centos上的错误主要就是我遇到的这几个你可以看下

吐血！人间不值得！我的脚本突然都挂了 ubuntu环境也用不了 奇了怪. 等我过两天大更新一波！
@NoOne-hub 兄弟你的好像也不正常了！

**Comment by shizeying** [comment]
大佬 centos可以试了吗

**Comment by NoOne-hub** [comment]
> > 好的我感觉centos上的错误主要就是我遇到的这几个你可以看下
> 
> 吐血！人间不值得！我的脚本突然都挂了 ubuntu环境也用不了 奇了怪. 等我过两天大更新一波！
> @NoOne-hub 兄弟你的好像也不正常了！

不可能的吧，这种全用pip安装的，版本对的上几乎不会出问题

**Comment by RainNameless** [comment]
> 大佬centos可以试了吗吗

已修复,可以了..  

@NoOne-hub 问个问题，只能内网访问是你做的限制吗？毕竟网页没有设置账号密码。这样的话他们要是服务器上的想挂代理可能就无法访问了. 
还有就是pyhthon环境,你用到了哪些模块,我新弄的系统不用virtualenv进行安装的话会报错, 我找错误发现是setup.py安装需要ez_setup.py模块的支持.安装好模块,就能安装setup.py了.
然后发现没报错可还是无法启动,还没去看supervisor的错误日志.
我先睡觉,看到麻烦帮我把脚本合并一下.谢谢！

**Comment by shizeying** [comment]
是直接用install.sh哇

**Comment by shizeying** [comment]
安装成功了,但是有个问题,我在输入自己v2ray客户端时候uuid这个环节只能默认生成,不能粘贴复制吗?如果不能的话我需要怎么做才能把uuid输入进行,难道要更换自己server端的uuid吗

**Comment by RainNameless** [comment]
> 安装成功了，但是有个问题，我在输入自己v2ray客户端时候UUID这个环节只能默认生成，不能粘贴复制吗？如果不能的话我需要怎么做才能把UUID输入进行，难道要更换自己的服务器端的UUID吗

我的是install_test.sh ,我发提交的还没合并更新,你可以去我的项目分支下载：https://github.com/RainNameless/v2ray_client

**Comment by NoOne-hub** [comment]
@shizeying 

> > 大佬centos可以试了吗吗
> 
> 已修复,可以了..
> 
> @NoOne-hub 问个问题，只能内网访问是你做的限制吗？毕竟网页没有设置账号密码。这样的话他们要是服务器上的想挂代理可能就无法访问了.
> 还有就是pyhthon环境,你用到了哪些模块,我新弄的系统不用virtualenv进行安装的话会报错, 我找错误发现是setup.py安装需要ez_setup.py模块的支持.安装好模块,就能安装setup.py了.
> 然后发现没报错可还是无法启动,还没去看supervisor的错误日志.
> 我先睡觉,看到麻烦帮我把脚本合并一下.谢谢！

是的，因为客户端没必要外网访问，或者他们可以copy本地配置上去就行了，后面那个报错的话，我也不清楚

**Comment by NoOne-hub** [comment]
> 安装成功了,但是有个问题,我在输入自己v2ray客户端时候uuid这个环节只能默认生成,不能粘贴复制吗?如果不能的话我需要怎么做才能把uuid输入进行,难道要更换自己server端的uuid吗

这个我的失误，忘了编辑部分，我改动下

**Comment by RainNameless** [comment]
> @shizeying
> 
> > > 大佬centos可以试了吗吗
> > 
> > 
> > 已修复,可以了..
> > @NoOne-hub 问个问题，只能内网访问是你做的限制吗？毕竟网页没有设置账号密码。这样的话他们要是服务器上的想挂代理可能就无法访问了.
> > 还有就是pyhthon环境,你用到了哪些模块,我新弄的系统不用virtualenv进行安装的话会报错, 我找错误发现是setup.py安装需要ez_setup.py模块的支持.安装好模块,就能安装setup.py了.
> > 然后发现没报错可还是无法启动,还没去看supervisor的错误日志.
> > 我先睡觉,看到麻烦帮我把脚本合并一下.谢谢！
> 
> 是的，因为客户端没必要外网访问，或者他们可以copy本地配置上去就行了，后面那个报错的话，我也不清楚

我觉得有必要加上，顺便把自定义账号密码跟端口的脚本加进去，毕竟不是每一台linux都有图形界面，这个应该还是需要的，你有时间加吗，我的话这两天也没时间了.

**Comment by RainNameless** [comment]
还有个bug更新你没合并.你看下.

**Comment by NoOne-hub** [comment]
> > @shizeying
> > > > 大佬centos可以试了吗吗
> > > 
> > > 
> > > 已修复,可以了..
> > > @NoOne-hub 问个问题，只能内网访问是你做的限制吗？毕竟网页没有设置账号密码。这样的话他们要是服务器上的想挂代理可能就无法访问了.
> > > 还有就是pyhthon环境,你用到了哪些模块,我新弄的系统不用virtualenv进行安装的话会报错, 我找错误发现是setup.py安装需要ez_setup.py模块的支持.安装好模块,就能安装setup.py了.
> > > 然后发现没报错可还是无法启动,还没去看supervisor的错误日志.
> > > 我先睡觉,看到麻烦帮我把脚本合并一下.谢谢！
> > 
> > 
> > 是的，因为客户端没必要外网访问，或者他们可以copy本地配置上去就行了，后面那个报错的话，我也不清楚
> 
> 我觉得有必要加上，顺便把自定义账号密码跟端口的脚本加进去，毕竟不是每一台linux都有图形界面，这个应该还是需要的，你有时间加吗，我的话这两天也没时间了.

我也没，到时候有时间更下，还有那些功能性更新

**Comment by NoOne-hub** [comment]
> 安装成功了,但是有个问题,我在输入自己v2ray客户端时候uuid这个环节只能默认生成,不能粘贴复制吗?如果不能的话我需要怎么做才能把uuid输入进行,难道要更换自己server端的uuid吗

更新了，可以修改uuid了

**Comment by shizeying** [comment]
要重新执行一遍install哇

**Comment by NoOne-hub** [comment]
不需要，只要把template这个文件夹替换

**Comment by shizeying** [comment]
![error](https://user-images.githubusercontent.com/38680988/65843153-a9685d00-e362-11e9-8bc9-46adeefdaa78.png)
![error2](https://user-images.githubusercontent.com/38680988/65843154-aa00f380-e362-11e9-8146-098744eed166.png)
要报如下异常,是怎么回事呢

**Comment by NoOne-hub** [comment]
> ![error](https://user-images.githubusercontent.com/38680988/65843153-a9685d00-e362-11e9-8bc9-46adeefdaa78.png)
> ![error2](https://user-images.githubusercontent.com/38680988/65843154-aa00f380-e362-11e9-8146-098744eed166.png)
> 要报如下异常,是怎么回事呢

已经修复

**Comment by NoOne-hub** [comment]
> > 大佬centos可以试了吗吗
> 
> 已修复,可以了..
> 
> @NoOne-hub 问个问题，只能内网访问是你做的限制吗？毕竟网页没有设置账号密码。这样的话他们要是服务器上的想挂代理可能就无法访问了.
> 还有就是pyhthon环境,你用到了哪些模块,我新弄的系统不用virtualenv进行安装的话会报错, 我找错误发现是setup.py安装需要ez_setup.py模块的支持.安装好模块,就能安装setup.py了.
> 然后发现没报错可还是无法启动,还没去看supervisor的错误日志.
> 我先睡觉,看到麻烦帮我把脚本合并一下.谢谢！

可以外网访问了，还有账号密码也设置了

**Comment by ne1000** [comment]
@NoOne-hub 
我也遇到这个问题了
unlink: cannot unlink ‘/run/supervisor.sock’: No such file or directory
Unlinking stale socket /tmp/supervisor.sock

启动
[root@localhost v2ray_client]# ps -aux|grep supervisord
root     15039  0.0  0.2 227764 17528 ?        Ss   11:21   0:00 /usr/bin/python3 /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf
root     15645  0.0  0.0 112708   992 pts/0    S+   11:29   0:00 grep --color=auto supervisord
[root@localhost v2ray_client]# netstat -ntlup | grep 8000
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      15041/python3

web能访问并添加了vmess链接但无法访问google，日志文件没有任何内容，怎么排查？

**Comment by NoOne-hub** [comment]
> @NoOne-hub
> 我也遇到这个问题了
> unlink: cannot unlink ‘/run/supervisor.sock’: No such file or directory
> Unlinking stale socket /tmp/supervisor.sock
> 
> 启动
> [root@localhost v2ray_client]# ps -aux|grep supervisord
> root 15039 0.0 0.2 227764 17528 ? Ss 11:21 0:00 /usr/bin/python3 /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf
> root 15645 0.0 0.0 112708 992 pts/0 S+ 11:29 0:00 grep --color=auto supervisord
> [root@localhost v2ray_client]# netstat -ntlup | grep 8000
> tcp 0 0 0.0.0.0:8000 0.0.0.0:* LISTEN 15041/python3
> 
> web能访问并添加了vmess链接但无法访问google，日志文件没有任何内容，怎么排查？

意思没有启动v2ray?你看下ps -ef|grep 'v2ray'
