### ISSUE TITLE
如果能出一个docker包就完美了。

### ISSUE THREAD

**Issue by ety001** [NoOne-hub/v2ray_client#18]
把程序封装成docker镜像，然后把sock和http端口映射出来使用。

**Comment by NoOne-hub** [comment]
这个是未来想法，现在先进行功能性测试

**Comment by ety001** [comment]
期待。

**Comment by NoOne-hub** [comment]
@ety001 已弄完docker封装，更简单的用法，项目里已给出网址，你也可以直接到我主页里找到docker_v2ray这个项目

**Comment by ety001** [comment]
@NoOne-hub 牛逼，等找个时间试试，有问题再开issue.
