### ISSUE TITLE
ubuntu18.04 使用错误

### ISSUE THREAD

**Issue by pingguokiller** [NoOne-hub/v2ray_client#21]
建议教程写得更简洁点，比如写了两种不同的启动方式，能否详细说明两种的区别，不然用户不知道到底用哪种启动，有何区别。最好只留下最便捷的步骤 1234

我在ubuntu18.04 环境下使用，有2个问题：
1.  按钮显示都是英文字母而不是图标
2.  订阅添加服务器之后，打开连接，红色状态变绿色，此时访问youtube.com无法访问。

**Comment by NoOne-hub** [comment]
@pingguokiller 两个脚本是因为安装部分曾经出了好多问题，多系统适配的问题，然后热心网友提供了个安装脚本，他测试过可以用，按钮都是英文字母能截个图嘛，那个状态你查看下配置文件，看修改没有

**Comment by NoOne-hub** [comment]
@pingguokiller 这个是因为老版本浏览器不适配的原因。我弄了只支持新版本的。。，我找时间更新下适配性，或者你换个浏览器版本应该就可以了，那个start过后没网你看下配置文件更改没有
