### ISSUE TITLE
ubuntu18.04 执行 install.sh 问题

### ISSUE THREAD

**Issue by zhengruiw02** [NoOne-hub/v2ray_client#22]
我每次运行sudo ./install.sh 发现都会在脚本的71行左右停住，提示内容大概如下

> Requirement already satisfied: meld3==2.0.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 12))
> Requirement already satisfied: python-dateutil==2.8.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 13))
> Requirement already satisfied: python-dotenv==0.10.3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 14))
> Requirement already satisfied: python-editor==1.0.4 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 15))
> Requirement already satisfied: six==1.12.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 16))
> Requirement already satisfied: SQLAlchemy==1.3.8 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 17))
> Requirement already satisfied: Werkzeug==0.15.5 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 18))
> Requirement already satisfied: supervisor==4.0.4 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 19))
> kill: (10916): No such process

后续内容我注释掉kill那一行，再执行，就是以下提示，根据提示按了ctrl+d后，也没执行到最后install.sh脚本的打印信息。

> Unlinking stale socket /tmp/supervisor.sock
> 接下来ctrl+d 退出
> v2rayClient                      STARTING  
> supervisor>

**Comment by NoOne-hub** [comment]
ok了，我改了下

**Comment by zhengruiw02** [comment]
试了新的版本可以完成安装。
