### ISSUE TITLE
如何设置监听ip？？？

### ISSUE THREAD

**Issue by jim12138** [NoOne-hub/v2ray_client#23]
想在树莓派上面运行与其他设备共享，但是监听ip似乎是127.0.0.1。。。
无法更新订阅

**Comment by NoOne-hub** [comment]
> 想在树莓派上面运行与其他设备共享，但是监听ip似乎是127.0.0.1。。。
> 无法更新订阅

可以在install.sh改那个0.0.0.0 默认就是监听这个的，订阅的话，是看网络问题，那个网址被墙的话可能也订阅不了

**Comment by jim12138** [comment]
多谢
