### ISSUE TITLE
http://localhost:9001 refused connection

### ISSUE THREAD

**Issue by xgdgsc** [NoOne-hub/v2ray_client#25]
`http://localhost:9001 refused connection` on  `sudo supervisorctl restart v2rayClient` on ubuntu 16.04, proxy not working, web UI works

**Comment by NoOne-hub** [comment]
看下关闭了的issue，那里可能对你有帮助

**Comment by NoOne-hub** [comment]
@xgdgsc

**Comment by xgdgsc** [comment]
要是搜索到了我就不会开新的了，请问哪个
