### ISSUE TITLE
您好，直接卡死了

### ISSUE THREAD

**Issue by appleyuchi** [NoOne-hub/v2ray_client#26]
请输入面板用户名(默认为NoOne-hub)

面板密码为(默认为1234567890):

Do you need to install v2rayCore?(Y/N)

./install.sh: 第 13 列： [: ==: 需要一元表示式
./install.sh: 第 13 列： [: ==: 需要一元表示式

Collecting alembic==1.1.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/9a/0f/a5e8997d58882da8ecd288360dddf133a83145de6480216774923b393422/alembic-1.1.0.tar.gz (1.0MB)
    0% |▎                               | 10kB 30kB/s eta 0:00:34^C
Operation cancelled by user

**Comment by NoOne-hub** [comment]
@appleyuchi 请问解决了没
