### ISSUE TITLE
页面上两个链接改一下，不然没办法反向代理

### ISSUE THREAD

**Issue by ChenYiZh** [NoOne-hub/v2ray_client#29]
<link rel="stylesheet" href="../static/css/mdui.min.css">
<script src="../static/js/mdui.min.js"></script>
中的“../”去掉，我的是子路径反向代理找不到文件，或者告诉我要改哪个文件，python的框架不是很熟

**Comment by ChenYiZh** [comment]
v2ray_client/app/templates/base.html是吧

**Comment by NoOne-hub** [comment]
> v2ray_client/app/templates/base.html是吧

是的，那是基本模板

**Comment by ChenYiZh** [comment]
可以的话，模板的url前面加个'.'，api也是，这样不会影响现在的跳转，不然真的很蛋疼，为了防电信查ip，我只能放在子路径下，跳转的还得自己加子路径就很麻烦

**Comment by ChenYiZh** [comment]
另外，有个需求，就是能不能有个登录界面，账号密码只要有地方配置，写死也没关系，不然，我现在的订阅信息是暴露在公网上的

**Comment by ChenYiZh** [comment]
原本install.py里面有面板密码，因为我在群晖那阉割的linux上安装的时候，有些指令不支持，删了，现在装工程目录下，我可以在哪个文件修改开启账号登陆？

**Comment by NoOne-hub** [comment]
> 可以的话，模板的url前面加个'.'，api也是，这样不会影响现在的跳转，不然真的很蛋疼，为了防电信查ip，我只能放在子路径下，跳转的还得自己加子路径就很麻烦

这个问题你可以自己改动了，我已经没时间维护了

**Comment by NoOne-hub** [comment]
> 另外，有个需求，就是能不能有个登录界面，账号密码只要有地方配置，写死也没关系，不然，我现在的订阅信息是暴露在公网上的

帐号密码在config.py里添加三行
BASIC_AUTH_USERNAME = "$user"
BASIC_AUTH_PASSWORD = "$passwd"
BASIC_AUTH_FORCE = True
这里user和passwd替换成你自己的
