### ISSUE TITLE
shell问题

### ISSUE THREAD

**Issue by shizeying** [NoOne-hub/v2ray_client#3]
你应该是用win编写的脚本文件,没有改成unix格式,在centos上会报错误:
-bash: ./install.sh: /bin/bash^M: bad interpreter: No such file or directory
需要改一哈

**Comment by NoOne-hub** [comment]
@shizeying 我是在linux上编写的脚本文件，用的pycharm，似乎是centos有这个问题，debian系列未出现
![image](https://user-images.githubusercontent.com/43596476/65309043-e479cc00-dbbd-11e9-9b28-7e95bc86fc31.png)
我按照网上的方法试了下，不知道可行否

**Comment by shizeying** [comment]
可以直接在notepad++中直接转换一下就可以了

**Comment by NoOne-hub** [comment]
@shizeying notepad++显示是unix格式

**Comment by shizeying** [comment]
创建虚拟环境（自选) virtualenv -p python3 venv
source venv/bin/activate
这两个可以不做哈

**Comment by shizeying** [comment]
建议在shell中加入virtualenv和另一个yum源,因为在安装过程中会报找不到改yum源,这样导致无法进行下去,从而必须要自己找到相对应的源了

**Comment by NoOne-hub** [comment]
> 建议在shell中加入virtualenv和另一个yum源,因为在安装过程中会报找不到改yum源,这样导致无法进行下去,从而必须要自己找到相对应的源了

修改了，环境都封装到项目里了
