### ISSUE TITLE
关于python3.8的支持

### ISSUE THREAD

**Issue by 3038922** [NoOne-hub/v2ray_client#32]
搜了下似乎3.8删了些函数.
我不太懂WEB开发.
我是ubuntu server .
默认apt update
python 就会被更新的.
```
ImportError: cannot import name 'escape' from 'cgi' (/usr/lib/python3.8/cgi.py)
```

**Comment by NoOne-hub** [comment]
> cannot import name 'escape' from 'cgi'

可以先试下docker版本, 这个问题暂时我也不清楚什么原因

**Comment by 3038922** [comment]
`https://stackoverflow.com/questions/58825230/importerror-cannot-import-name-escape-from-cgi`
怎么弄DOCK版本啊?我是嵌入式机器人控制那块  这WEB开发云里雾里....
能给我个DOCKER下载命令不....
docker我是装了...-.-

**Comment by NoOne-hub** [comment]
> `https://stackoverflow.com/questions/58825230/importerror-cannot-import-name-escape-from-cgi`
> 怎么弄DOCK版本啊?我是嵌入式机器人控制那块 这WEB开发云里雾里....
> 能给我个DOCKER下载命令不....
> docker我是装了...-.-

https://github.com/NoOne-hub/docker_v2ray 项目描述里有

**Comment by 3038922** [comment]
谢谢你啊
