### ISSUE TITLE
安装完成后,会报python不匹配错误

### ISSUE THREAD

**Issue by shizeying** [NoOne-hub/v2ray_client#4]
这里的原因应该是系统使用了py2,而你的事py3的原因,所以可不可以改变一下其中的配置,让其自动适应py3,这样的话在安装完成之后直接匹配py3,而不是py2,我用的系统是centos7

![Uploading TIM图片20190920110246.png…]()

**Comment by NoOne-hub** [comment]
@shizeying 请用虚拟环境测试下是否可以，我用虚拟环境未出现这个问题，图片看不到

**Comment by shizeying** [comment]
你的python是怎么安装的呢?我安装好之后无法启动

**Comment by NoOne-hub** [comment]
@shizeying readme里有说明呢，
virtualenv -p python3 venv
source venv/bin/activate
在虚拟环境里默认是python3,在sudo ./install.sh

**Comment by shizeying** [comment]
Error: .ini file does not include supervisord section
For help, use /usr/local/bin/supervisord -h
[root@localhost conf.d]# supervisorctl -c /etc/supervisor/supervisord.conf
Error: .ini file does not include supervisorctl section
For help, use /usr/local/bin/supervisorctl -h
请问你这个是怎么处理的呢

**Comment by NoOne-hub** [comment]
> Error: .ini file does not include supervisord section
> For help, use /usr/local/bin/supervisord -h
> [root@localhost conf.d]# supervisorctl -c /etc/supervisor/supervisord.conf
> Error: .ini file does not include supervisorctl section
> For help, use /usr/local/bin/supervisorctl -h
> 请问你这个是怎么处理的呢

这不是python错误，这是supervisorctl的错误，我已在新版本的安装脚本中添加对centos这部分的修改

**Comment by shizeying** [comment]
刚修改的吗

**Comment by NoOne-hub** [comment]
> 刚修改的吗

是的，我将我这边的配置文件写入，不知道centos和arch安装的supervisor这么多问题

**Comment by shizeying** [comment]
你可以发我一份,我来测试下

**Comment by NoOne-hub** [comment]
> 你可以发我一份,我来测试下

在项目里已经更新，你可以只下载install.sh

**Comment by shizeying** [comment]
supervisor这次修改之后这个是不是不需要自己安装呢

**Comment by NoOne-hub** [comment]
> supervisor这次修改之后这个是不是不需要自己安装呢

不需要吧，脚本里会装

**Comment by shizeying** [comment]
您好!你要不要在看下呢当运行到Do you need to install v2rayCore?(Y/N)选择Y之后,就不动了,网络也是通的,我等了大概一个多小时都没动
