### ISSUE TITLE
ubuntu18.04在依赖包安装完成后报错（急求帮助，万分感谢）

### ISSUE THREAD

**Issue by JutunYu** [NoOne-hub/v2ray_client#5]
45到49行
function install_others() {
#安装依赖
install_v2ray
pip3 install -r requirements.txt
pip3 install gunicorn
之后

Error: File contains parsing errors: /etc/supervisor/conf.d/v2rayClient.conf
             [line 2]: 'command=gunicorn -b localhost:8000 -w 4 v2rayClient:app\n'
             ...                               #此处还有5行提示
             [line 8]: 'killasgroup=true\n'
                                               #以上是路径 /etc/supervisor/conf.d 之中 v2rayClient.conf里的内容
For help, use /usr/bin/supervisord -h
接下来输入update，然后ctrl+d退出
unix:///var/run/supervisor.sock no such file     #缺失文件？？
然后可以输入 update 但接着报错：
error: <class 'socket.error'>, [Error 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 288
继续输入update依然如此
我就只能ctrl+d了，之后的步骤应该也没有完成。

![image](https://user-images.githubusercontent.com/32646005/65369789-4f8dd600-dc84-11e9-87b9-952d2d0aa36d.png)

在网上有找到类似相关问题：
https://blog.csdn.net/baidu_36639782/article/details/86304011
不知道有没有帮助。

**Comment by JutunYu** [comment]
我看了一下，好像和manjaro kde的那个老哥有相似的麻烦，其实我上午装的时候，没有error 2，但不知道为什么重启之后就有了。很微妙倒是。

**Comment by NoOne-hub** [comment]
> 我看了一下，好像和manjaro kde的那个老哥有相似的麻烦，其实我上午装的时候，没有error 2，但不知道为什么重启之后就有了。很微妙倒是。

这个错误，supervisor这个我也犯，所以我才有update那一说，那个是我查阅资料后，发觉没问题才弄出来的，请问你的/etc/supervisor/conf.d/里存有v2rayClient这个文件没有，还有/etc/supervisor里有conf文件没

**Comment by NoOne-hub** [comment]
> 我看了一下，好像和manjaro kde的那个老哥有相似的麻烦，其实我上午装的时候，没有error 2，但不知道为什么重启之后就有了。很微妙倒是。

那个sock错误很多人都有，只要命令不出错就可以解决，这是他程序本身的问题？

**Comment by JutunYu** [comment]
我检查了，都没有缺的文件。

https://www.jianshu.com/p/b211a7bb528a
https://blog.csdn.net/qq_28885149/article/details/79364685

这里面提到的问题我也没有遇到。

**Comment by JutunYu** [comment]
而且kill不了进程，pid一直在变

**Comment by JutunYu** [comment]
![image](https://user-images.githubusercontent.com/32646005/65375446-7c63dc80-dcc8-11e9-9c41-7d3bc6157194.png)
![image](https://user-images.githubusercontent.com/32646005/65375458-ab7a4e00-dcc8-11e9-8305-5e64b35702ed.png)


https://zvv.me/z/1230.html 我参考了一下这个，解决了一点点？我猜。。。 虽然解决的办法很粗暴。

但还有新的问题出现

**Comment by RainNameless** [comment]
> ![图片](https://user-images.githubusercontent.com/32646005/65375489-eda38f80-dcc8-11e9-8ce9-d6e51a435abe.png)
> 
> https://zvv.me/z/1230.html我参考了一下这个，解决了一点点？我猜。。。虽然解决的办法很粗暴。
> 
> 但还有新的问题出现

报错你就执行这个 unlink /run/superviso.sock
如果路径不是这个你就【 find / -name “superviso.sock” 】查下路径cd /进去在目录里直接 【unlink superviso.sock】

**Comment by JutunYu** [comment]
unlink之后 再重新install一下？

**Comment by JutunYu** [comment]
![image](https://user-images.githubusercontent.com/32646005/65376480-e8e3d900-dcd2-11e9-956c-3005d2760c80.png)
也没能解决这个问题。

**Comment by JutunYu** [comment]
![image](https://user-images.githubusercontent.com/32646005/65381634-27f04980-dd28-11e9-9166-7cdc3679cd62.png)
今早操作一下以后到了这一步。之后如何运行呢

（可以通过telegram联系您吗～

**Comment by RainNameless** [comment]
> ![图片](https://user-images.githubusercontent.com/32646005/65381634-27f04980-dd28-11e9-9166-7cdc3679cd62.png)
> 今早操作一下以后到了这一步。之后如何运行呢
> 
> （可以通过电报联系您吗〜

可以的Telegram:https://t.me/NamelessRain

**Comment by JutunYu** [comment]
telegram现在的限制好像不可以86互相私信在没有提前互相添加的情况下。
https://t.me/jutunyu这是我，或者
https://t.me/joinchat/AAAAAEt-LTkL8HKvUPvHjg 加这个群吧。

**Comment by NoOne-hub** [comment]
> ![image](https://user-images.githubusercontent.com/32646005/65376480-e8e3d900-dcd2-11e9-956c-3005d2760c80.png)
> 
> ![image](https://user-images.githubusercontent.com/32646005/65376616-a0c5b600-dcd4-11e9-950e-6b8cbb08325b.png)
> 
> 也没能解决这个问题。

这个周末没时间，等多几天，我把你们提的汇总下，测试一波在更新

**Comment by RainNameless** [comment]
![Snipaste_2019-09-23_17-38-08](https://user-images.githubusercontent.com/43627188/65415848-2a869800-de29-11e9-9ee6-34bc6393aaad.png)
@JutunYu @NoOne-hub 
我踩出来了!你的脚本有点乱！我重新写了一遍.= = ！

**Comment by NoOne-hub** [comment]
@JutunYu 现在可以测试下安装脚本
