### ISSUE TITLE
ubuntu16.04

### ISSUE THREAD

**Issue by Lu-mo** [NoOne-hub/v2ray_client#6]
Error: File contains parsing errors: /etc/supervisor/conf.d/v2rayClient.conf
	[line  2]: '    command=gunicorn -b localhost:8000 -w 4 v2rayClient:app\n'
	[line  3]: '    directory=/home/lumo/\xe6\xa1\x8c\xe9\x9d\xa2/v2ray_client-master\n'
	[line  4]: '    user=root\n'
	[line  5]: '    autostart=true\n'
	[line  6]: '    autorestart=true\n'
	[line  7]: '    stopasgroup=true\n'
	[line  8]: '    killasgroup=true\n'
For help, use /usr/bin/supervisord -h
接下来输入update,然后ctrl+d 退出
supervisor> update
error: <class 'xmlrpclib.Fault'>, <Fault 92: "CANT_REREAD: File contains parsing errors: /etc/supervisor/conf.d/v2rayClient.conf\n\t[line  2]: '    command=gunicorn -b localhost:8000 -w 4 v2rayClient:app\\n'\n\t[line  3]: '    directory=/home/lumo/\\xe6\\xa1\\x8c\\xe9\\x9d\\xa2/v2ray_client-master\\n'\n\t[line  4]: '    user=root\\n'\n\t[line  5]: '    autostart=true\\n'\n\t[line  6]: '    autorestart=true\\n'\n\t[line  7]: '    stopasgroup=true\\n'\n\t[line  8]: '    killasgroup=true\\n'">: file: /usr/lib/python2.7/xmlrpclib.py line: 800

**Comment by RainNameless** [comment]
希望得到更全面 从执行./install 后的所有命令提示

**Comment by NoOne-hub** [comment]
> 希望得到更全面 从执行./install 后的所有命令提示

这个周末没时间，等多几天，我把你们提的汇总下，测试一波在更新

**Comment by NoOne-hub** [comment]
@Lu-mo 测试下
