### ISSUE TITLE
请求添加对KALI_linux的支持

### ISSUE THREAD

**Issue by podm1n** [NoOne-hub/v2ray_client#8]
（venv) root@kali:~/v2ray_client# sudo ./install.sh
Platform type: Linux
Linux distro: Unknow
Not support linux distro: Unknow
It takes 0 minutes.
success
now you can open you web browser,open http://127.0.0.1:8000

**Comment by NoOne-hub** [comment]
> （venv) root@kali:~/v2ray_client# sudo ./install.sh
> Platform type: Linux
> Linux distro: Unknow
> Not support linux distro: Unknow
> It takes 0 minutes.
> success
> now you can open you web browser,open http://127.0.0.1:8000

这个周末没时间，等多几天，我把你们提的汇总下，测试一波在更新

**Comment by RainNameless** [comment]
> > （venv）root @ kali：〜/ v2ray_client＃sudo ./install.sh 
> > 平台类型：Linux 
> > Linux发行版：未知
> > 不支持linux发行版：未知
> > 需要0分钟。
> > 成功
> > 现在您可以打开网络浏览器，打开http://127.0.0.1:8000
> 
> 这个周末没时间，等多几天，我把你们提的汇总下，测试一波在更新

你教我手动配置一波,我来完善脚本。不然虽然没报错了,可无从下手排查。之前没用过supervisor!!!

**Comment by NoOne-hub** [comment]
@podm1n kali也支持了
