### ISSUE TITLE
我写了新脚本

### ISSUE THREAD

**Issue by RainNameless** [NoOne-hub/v2ray_client#9]
@NoOne-hub ，试试看我这个的出错概率，还没怎么测试 可觉得挺稳 嘿嘿！

**Comment by NoOne-hub** [comment]
已上传，我正在重新构建用这个的方法，看用pip安装的会不会搞的定

**Comment by RainNameless** [comment]
@NoOne-hub 脚本更改了点bug，权限你帮我加完权限然后用git传上去吧，我在Windows_网页端直接上传就变成普通文档了，我这个电脑没git，懒得去配置了，有劳你.

**Comment by NoOne-hub** [comment]
@RainNameless 啥权限问题

**Comment by RainNameless** [comment]
@NoOne-hub 没有执行权限,进去得自己chmod -R 777 install_test.sh
